vich_uploader:
    db_driver: orm
    mappings:
        album_images:
            uri_prefix: '%album_images%'
            upload_destination: '%kernel.project_dir%/public%album_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            